# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'JetBeepDeviceSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'JetBeepDeviceSDK' #, :podspec => '../'
end
